version: '3.8'
volumes:
    pg_data:

services:
  web:
      build: .
      ports:
          - "8000:8000"
      depends_on:
          - db

  db:
      image: postgres:13-alpine
      volumes:
        - pg_data:/var/lib/postgresql/data
      environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restaurants
      ports:
          - "5432:5432"